# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert_engine', '0002_auto_20161222_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
