# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert_engine', '0003_auto_20161222_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
